# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a895c4ad831ac53c46b6a71a1921b37748cb233631054d34e2df1f536f6154153c94863623ab259fc7558bbef6579fd048533376a69968bdde1916a34505d958

test:
  secret_key_base: 1eeb2eb55e27d70aeb904e7f2cfa107427df70d972b55a0dbdcb7ba46d2cd2641d7da7751a96539ded7edd9ebf9ce634c3c847902fc520fecde1426674ea2a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
